#===============================================================================
# Custom Map Metadata (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New map metadata created via Debug will appear here.
#===============================================================================

