#===============================================================================
# Custom Encounter Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New encounters created via Debug will appear here.
#===============================================================================

