#===============================================================================
# Custom Move Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New moves created via Debug will appear here.
#===============================================================================

