#===============================================================================
# Custom TrainerType Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New trainer types created via Debug will appear here.
#===============================================================================

