#===============================================================================
# Custom Trainer Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New trainers created via Debug will appear here.
#===============================================================================

