#===============================================================================
# Custom Pokemon Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New Pokemon created via Debug will appear here.
#===============================================================================

