#===============================================================================
# Custom Ability Definitions (Debug Generated)
#===============================================================================
# Auto-generated by Debug menu. Edit with care.
# New abilities created via Debug will appear here.
#===============================================================================

